@startuml main
  left to right direction

  class "User" as u {
    - id: Long
    - name: String
    - admin: boolean
    - results: Set<Result>
  }

  class "Race" as r {
    - id: Long
    - title: String
    - description: String
    - duration: Integer
    - questions: Set<Question>
    - results: Set<Result>
  }

  class "Question" as q {
    - id: Long
    - statement: String
    - points: Integer
    - race: Race
    - answers: List<String>
    - correctAnswer: Integer
  }

  class "Result" as re {
    - id: Long
    - participant: User
    - race: Race
    - answeredQuestions: Set<AnsweredQuestion>
    - points: Integer
    - answeredAt: LocalDateTime
  }

  class "AnsweredQuestion" as aq {
    - id: Long
    - result: Result
    - question: Question
    - answeredCorrectly: boolean
  }

  r "1..1" *--- "1..*" q

  re "0..*" o-- "1..1" u
  re "0..*" o--- "1..1" r

  re "1..1" *-- "1..*" aq
  aq "0..*" o--- "1..1" q

@enduml
